### ISSUE TITLE
Todo frontend v2

### ISSUE THREAD

**Issue by sirodoht** [OKThess/website#52]
* [x] Finalize language switch
* [x] Add mentor fields in model
* [x] Program: move about above side-nav
* [x] Meetup page in events page
* [x] Add meetup page
* [x] Old events dimmed out
* [x] Fix slider arrows
* [x] Read more buttons should be level
* [x] WYSIWYG editor for blog post
* [x] Each post in two languages
* [x] Past events with month names
* [x] Fix event links and date position
* [x] Open accordion from the link
* [x] Program: add industries js filter
